version: '3.8'

services:
  ids-edge:
    build: .
    container_name: edge_ids_ips
    restart: unless-stopped
    # MODO HOST: Crítico para que la tarjeta detecte el tráfico real de la Raspberry y Streamlit se sirva en la IP real.
    network_mode: "host"
    # Privilegios necesarios para sniffear paquetes en Linux sin hacer el contenedor privilegiado entero
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Crítico para el ARP Spoofing: Permite que el contenedor actúe como router y reenvíe tráfico
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      # Persistencia de la base de datos (se guardará en la carpeta local data/)
      - ./data:/app/data
    environment:
      - IDS_LOG_LEVEL=INFO
      # Permitimos que coja la interfaz del entorno, y si no, por defecto a wlan0 (muy común en Raspberry)
      # Puedes cambiarlo a eth0 si usas cable: IDS_CAPTURE_IFACE=eth0 docker-compose up -d
      - IDS_CAPTURE_IFACE=${IDS_CAPTURE_IFACE:-wlan0}
      - IDS_MODEL=random_forest
